spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t7mMfqNL8jVyVtVvScG
      secret-key: NCs17NTEernVuYLGTT11veUZmtKtsz
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-jiyonngfei

  application:
    name: gulimall-third-party

server:
  port: 30000
